### ISSUE TITLE
Adding SSL Support for VSDB

### ISSUE THREAD

**Issue by camjac251** [theChaosCoder/avsrepo#3]
Would it be possible to add encryption to the http://vsdb.top website? I could help with that if needed. CloudFlare offers free SSL encryption and creating one for the route between the server and cloudflare is really easy with `certbot` for Let's Encrypt (It has a cloudflare dns plugin for domain verification and can also configure your site block for Apache and Nginx automatically)

With having user authentication available through the website, it's crucial to have SSL forced for that to prevent any sniffing attempts of users.

**Comment by theChaosCoder** [comment]
It's not really needed since there a only 2 accounts and all data is public anyway. Even the second account.

I will think about it.

**Comment by camjac251** [comment]
If it's the setup part that is deterring let me know and I can help

**Comment by theChaosCoder** [comment]
done
