### ISSUE TITLE
Disabling Checks

### ISSUE THREAD

**Issue by camjac251** [theChaosCoder/avsrepo#4]
AppVeyor is being ran as a check for the main branch. Is it possible to disable it since it is not configured?

**Comment by camjac251** [comment]
As an alternative to AppVeyor for building, GitHub Actions support python and could be used with PyInstaller to generate new builds when the code is updated.

https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
https://github.community/t5/GitHub-Actions/Build-Python-app-with-PyInstaller-in-Github-Actions/td-p/39616

**Comment by theChaosCoder** [comment]
It's on my todo list. I wanted to test appveyer but in the end I just build avsrepo.exe in a 32bit windows VM. 
Another idea is to check if a commited update / new package is valid and then auto push a new compiled avspackages.json. Makes more sense if more people will commit something.

That means it has to be checked whether
- avspackages.json can be compiled without errors
- the latest commit can be "installed"  ( hash + url must be valid)

**Comment by camjac251** [comment]
GitHub actions should work out though

**Comment by theChaosCoder** [comment]
appveyor is disabled
