### ISSUE TITLE
Test optimized pyinstaller builds

### ISSUE THREAD

**Issue by theChaosCoder** [theChaosCoder/avsrepo#6]
https://pyinstaller.readthedocs.io/en/stable/usage.html#running-pyinstaller-with-python-optimizations

and with upx...

**Comment by camjac251** [comment]
Hopefully https://github.com/theChaosCoder/avsrepo/pull/9 will solve it.

**Comment by theChaosCoder** [comment]
With upx the startup time is abysmal.
